version: "3.0"

services:
  app:
    restart: on-failure
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
        - ./.env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"